- hosts: all
  become: true
  tasks:

  - name: Create ansible user account
    user:
      name: ansible
      group: sudo
      uid: 990
      state: present

  - name: Add ansible ssh key
    authorized_key:
      user: ansible
      state: present
     # key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/ansible.pub') }}"
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKprg2uox/DhJ56FmRUUU5kH+vo4A4+5Gcx6kFbOBDvK ansible"

  - name: Create sudoers file for ansible user
    copy:
      content: 'ansible ALL=(ALL:ALL) NOPASSWD:ALL'
      dest: /etc/sudoers.d/ansible
      mode: 0440       