- name: Ensure docker-compose directory is created
  file:
    path: "{{ compose_path }}"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: 0775

- name: Copy docker-compose file to host
  copy:
    src: "{{ ansible_hostname }}/docker-compose.yml"
    dest: "{{ compose_path }}/docker-compose.yml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: 0660
    
- name: Create containers based on docker-compose template
  community.general.docker_compose:
    pull: yes
    recreate: smart
    remove_orphans: yes
    project_src: "{{ compose_path }}"
  environment: "{{ docker_env }}"
    