## geerlingguy.docker

traefik_required: true

docker_env:
  DOMAINNAME: "{{ public_domain }}"
  CLOUDFLARE_EMAIL: "{{ cloudflare_email }}"
  CLOUDFLARE_API_KEY: "{{ cloudflare_api_key }}"
  USERDIR: "{{ appdata_path }}"
  PUID: "{{ main_uid }}"
  PGID: "{{ main_gid }}"
  TZ: "{{ TZ }}"
  GOOGLE_CLIENT_ID: "{{ google_client_id }}"
  GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
  OAUTH_SECRET: "{{ oauth_secret }}"
  MY_EMAIL: "{{ whitelist_email }}"
  URL_PATH: "{{ oauth_url_path }}"
  RADARR_API_KEY: "{{ radarr_api_key }}"
  SONARR_API_KEY: "{{ sonarr_api_key }}"

mount:
  path: /mnt/media
  fstype: nfs
  src: "{{ hostvars['fs01']['ansible_default_ipv4']['address'] }}:/mnt/media"

   